/*
**  mod_colormap.c -- Apache sample colormap module
**  [Autogenerated via ``apxs -n colormap -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory
**  by running:
**
**    $ apxs -c -i mod_colormap.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /colormap in as follows:
**
**    #   apache2.conf
**    LoadModule colormap_module modules/mod_colormap.so
**    <Location /colormap>
**    SetHandler colormap
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /colormap and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/colormap
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**
**    The sample page from mod_colormap.c
*/

#include <sstream>

#include "httpd.h"
#include "http_config.h"
#include "http_core.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "util_script.h"

#include "../randomtrip/point.h"
#include "../randomtrip/visited.h"

using std::ostringstream;
using std::stod;
using std::string;
using std::hex;

double get_double(apr_table_t* GET, const char* param, double def) {
  auto* value = apr_table_get(GET, param);
  if (value) {
    def = stod(value);
  }
  return def;
}

Visited get_visited(apr_table_t* GET, const char* param, Visited def) {
  auto* value = apr_table_get(GET, param);
  if (value) {
    def = Visited(value);
  }
  return def;
}

void mapslatlon(ostringstream& html, Point point) {
  html << "new google.maps.LatLng(" << point.String() << ")";
}

void rectangle(ostringstream& html, Point start, Point end, string color) {
  html << "    rectangle = new google.maps.Rectangle({\n\
        strokeColor: ";
  html << color;
  html << ",\n\
        strokeOpacity: 0.0,\n\
        fillColor: ";
  html << color;
  html << ",\n\
        fillOpacity: 0.75,\n\
        map: map,\n\
    });\n\
    rectangle.setBounds(new google.maps.LatLngBounds(\n\
        ";
  mapslatlon(html, start);
  html << ",\n\
        ";
  mapslatlon(html, end);
  html << "));\n\
\n";
}

const string get_html(Point start, Point end, Visited visited) {
  ostringstream html;
  html << "<!DOCTYPE html>\n\
<html>\n\
  <head>\n\
    <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\">\n\
    <meta charset=\"utf-8\">\n\
    <title>Wild Journey</title>\n\
    <style>\n\
      html, body, #map-canvas {\n\
        height: 100%;\n\
        margin: 0px;\n\
        padding: 0px\n\
      }\n\
    </style>\n\
    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\n\
    <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCU5S0FYwhr4fLRRCQNHI5ZkFkSdmOrFKA\"></script>\n\
    <script type=\"text/javascript\">\n\
function initialize() {\n\
    map = new google.maps.Map(document.getElementById('map-canvas'), {\n\
        mapTypeId: google.maps.MapTypeId.TERRAIN\n\
    });\n\
\n\
    map.setZoom(0);\n\
    map.setCenter(new google.maps.LatLng(0,0));\n\
\n";
  auto parts = 50;
  auto lat_step = (end.lat_ - start.lat_) / parts;
  double max = 0;
  for (auto lat = start.lat_ + lat_step/2; lat <= end.lat_ - lat_step/2; lat += lat_step) {
    auto lon_step = (end.lon_ - start.lon_) / parts;
    for (auto lon = start.lon_ + lon_step/2; lon <= end.lon_ - lon_step/2; lon += lon_step) {
      auto current = visited.MinDistance(Point(lat, lon));
      if (current > max) {
        max = current;
      }
    }
  }
  for (auto lat = start.lat_ + lat_step/2; lat <= end.lat_ - lat_step/2; lat += lat_step) {
    auto lon_step = (end.lon_ - start.lon_) / parts;
    for (auto lon = start.lon_ + lon_step/2; lon <= end.lon_ - lon_step/2; lon += lon_step) {
      auto current = visited.MinDistance(Point(lat, lon));
      ostringstream color;
      color << "'#";
      int value = 256 - current / max * 256;
      if (value == 256) {
        value--;
      }
      color.width(2);
      color.fill('0');
      color << hex << value;
      value = current / max * 256;
      if (value == 256) {
        value--;
      }
      color.width(2);
      color.fill('0');
      color << hex << value;
      color << "00'";
      rectangle(html,
                Point(lat - lat_step/2, lon - lon_step/2),
                Point(lat + lat_step/2, lon + lon_step/2),
                color.str());
    }
  }
  html << "}\n\
\n\
$(function () {\n\
    google.maps.event.addDomListener(window, 'load', initialize);\n\
});\n\
    </script>\n\
  </head>\n\
  <body>\n\
    <div id=\"map-canvas\"></div>\n\
  </body>\n\
</html>\n\
     ";
  return html.str();
}

/* The sample content handler */
static int colormap_handler(request_rec *r)
{
  if (strcmp(r->handler, "colormap")) {
    return DECLINED;
  }
  r->content_type = "text/html";
  if (!r->header_only) {
    apr_table_t* GET;
    ap_args_to_table(r, &GET);
    ap_rputs(get_html(Point(get_double(GET, "slat", -90), get_double(GET, "slon", -180)),
                      Point(get_double(GET, "elat", 90), get_double(GET, "elon", 180)),
                      get_visited(GET, "visited", Visited())).c_str(),
             r);
  }
  return OK;
}

static void colormap_register_hooks(apr_pool_t *p)
{
  ap_hook_handler(colormap_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA colormap_module = {
  STANDARD20_MODULE_STUFF,
  NULL,                  /* create per-dir    config structures */
  NULL,                  /* merge  per-dir    config structures */
  NULL,                  /* create per-server config structures */
  NULL,                  /* merge  per-server config structures */
  NULL,                  /* table of config file commands       */
  colormap_register_hooks  /* register hooks                      */
};
