/*
**  mod_randomtrip.c -- Apache sample randomtrip module
**  [Autogenerated via ``apxs -n randomtrip -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory
**  by running:
**
**    $ apxs -c -i mod_randomtrip.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /randomtrip in as follows:
**
**    #   apache2.conf
**    LoadModule randomtrip_module modules/mod_randomtrip.so
**    <Location /randomtrip>
**    SetHandler randomtrip
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /randomtrip and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/randomtrip
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**
**    The sample page from mod_randomtrip.c
*/

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
static int randomtrip_handler(request_rec *r)
{
    if (strcmp(r->handler, "randomtrip")) {
        return DECLINED;
    }
    r->content_type = "text/html";

    if (!r->header_only)
        ap_rputs("\
<!DOCTYPE html>\n\
<html>\n\
  <head>\n\
    <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\">\n\
    <meta charset=\"utf-8\">\n\
    <title>Wild Journey</title>\n\
    <style>\n\
      html, body, #map-canvas {\n\
        height: 100%;\n\
        margin: 0px;\n\
        padding: 0px\n\
      }\n\
    </style>\n\
    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\n\
    <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCU5S0FYwhr4fLRRCQNHI5ZkFkSdmOrFKA\"></script>\n\
    <script type=\"text/javascript\">\n\
function initialize() {\n\
    this.map = new google.maps.Map(document.getElementById('map-canvas'), {\n\
        mapTypeId: google.maps.MapTypeId.TERRAIN\n\
    });\n\
    this.map.setZoom(0);\n\
    this.map.setCenter(new google.maps.LatLng(0, 0));\n\
\n\
    this.rectangle = new google.maps.Rectangle({\n\
        strokeColor: '#FF0000',\n\
        strokeOpacity: 0.8,\n\
        strokeWeight: 2,\n\
        fillColor: '#FF0000',\n\
        fillOpacity: 0.35,\n\
        map: this.map,\n\
    });\n\
    this.rectangle.setBounds(new google.maps.LatLngBounds(\n\
        new google.maps.LatLng(-90, -180),\n\
        new google.maps.LatLng(90, 180)));\n\
\n\
    this.marker = new google.maps.Marker({\n\
        map: this.map\n\
    });\n\
    this.marker.setPosition(new google.maps.LatLng(0, 0));\n\
}\n\
\n\
function setLink(link) {\n\
    $(\"#link\").text(link);\n\
    $(\"#link\").attr('href', link);\n\
}\n\
\n\
$(function () {\n\
    setLink(location.href);\n\
    google.maps.event.addDomListener(window, 'load', initialize);\n\
});\n\
    </script>\n\
  </head>\n\
  <body>\n\
    <form id=\"dice\" action=\".\">\n\
        <input id=\"dice-value\" type=\"text\" name=\"value\">\n\
        <input type=\"submit\" value=\"go\">\n\
    </form>\n\
    <a id=\"reset\" href=\"#\">reset</a>\n\
    <div id=\"info\">(0, 0)</div>\n\
    <a id=\"link\" href=\"#\">link</a>\n\
    <div id=\"map-canvas\"></div>\n\
  </body>\n\
</html>\n\
", r);
    return OK;
}

static void randomtrip_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(randomtrip_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA randomtrip_module = {
    STANDARD20_MODULE_STUFF,
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    randomtrip_register_hooks  /* register hooks                      */
};

